### ISSUE TITLE
Undefined offset: 1 

### ISSUE THREAD

**Issue by jcalonso** [NicolasMahe/Laravel-SlackOutput#1]
Hi,

I was installing this package on Lumen, after solving some issues with the configuration, I'm having the following error after adding the Scheduled commands reporting:

```
SlackOutput::scheduledCommand(
            $schedule->command('command:my-command)->daily()
        );
```

After digging a little bit more, I found that in this line:
https://github.com/NicolasMahe/Laravel-SlackOutput/blob/master/src/Service.php#L63
is using a pattern like this `'artisan '` but in my current Lumen app the `$event->command` value is:
`'/usr/bin/php5' artisan command:my-command` (without the single quote around artisan)

I was just wondering if you know why I get this different? is because Lumen? Would it be possible to handle both cases to support Lumen? Or is there anything else wrong?

Let me know if you have any ideas.

**Comment by NicolasMahe** [comment]
Fixed with PR #2
